version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:629982420099:task-definition/ecs-demo:1"
        LoadBalancerInfo:
          ContainerName: "sample-website"
          ContainerPort: 80
